### PR TITLE
Fix out-of-memory issue in creating our pg_restore list file.

### LINKED ISSUE #811: Error:Failed to create pg_restore list file : out of memory
Migration failing with OOM error while reading whole list file in-memory .
```
2024-06-06 21:13:59.896 69 ERROR  dump_restore.c:781        Failed to create pg_restore list file: out of memory
2024-06-06 21:13:59.896 69 ERROR  dump_restore.c:212        Failed to prepare the pg_restore --use-list catalogs, see above for details
2024-06-06 21:13:59.896 69 ERROR  cli_clone_follow.c:600    Failed to prepare schema on the target database, see above for details
2024-06-06 21:13:59.896 69 ERROR  cli_clone_follow.c:506    Failed to clone source database, see above for details
2024-06-06 21:14:00.062 51 ERROR  cli_clone_follow.c:768    clone process 69 has terminated [6]
```

Code path - https://github.com/dimitri/pgcopydb/blob/022f2a37f2317fc19c5376e7c9b5fb110e2c5286/src/bin/pgcopydb/dump_restore.c#L799
I also found similar error 

Discussion with Dimitri:
The error message actually comes from the pgcopydb source code, so that's a problem with memory handling within pgcopydb itself. At the moment the strategy that has been implemented consists of reading the whole list file in-memory, and then parsing it line by line (walking through an array), preparing a new version of it in memory again, only to write that memory to disk at the end.
 
I think it would be fairly easy to replace that mechanism with line-by-line reading of the file using [fgets](https://man7.org/linux/man-pages/man3/fgets.3p.html) instead of fread(), and then writing the line with fwrite() rather than accumulating in-memory.

### PR DESCRIPTION
**Pull request by dimitri**
Instead of creating the whole contents of the file in-memory, write it to disk one line at a time, keeping only that line in-memory during the whole operation.

Also arrange to code to only read the pg_restore --list output one line at a time, no context is needed to be able to parse this file format (pg_dump archive Table Of Contents).

Fixes #811 
Replaces and closes #818

### CODE REVIEW

File: src/bin/pgcopydb/file_utils.h [hunk 1]
```diff
@@ -54,6 +54,26 @@ bool write_file(char *data, long fileSize, const char *filePath);
 bool append_to_file(char *data, long fileSize, const char *filePath);
 bool read_file(const char *filePath, char **contents, long *fileSize);
 bool read_file_if_exists(const char *filePath, char **contents, long *fileSize);
+
+/* iterate over a file one line at a time */
+typedef bool (FileIterLinesFun)(void *context, char *line);
+
+bool file_iter_lines(const char *filename, size_t bufsize,
+					 void *context,
+					 FileIterLinesFun *callback);
```
Comment (hanefi) [inline src/bin/pgcopydb/file_utils.h:63]: Why do we have a function declaration and definition if it is not used anywhere in the codebase?

Comment (dimitri) [reply src/bin/pgcopydb/file_utils.h:63]: The idea is that we have other places where we read a file line-by-line that could benefit from this iterator and one-line-at-a-time in memory approach. Also to implement the full iterator protocol, even though the composition with the archive iterator needs to be “open-coded” at the moment, using the lower-level API directly.
